---
  - name: allow ssh and https access to new hosts
    ec2_group:
      name: awsnd_public
      description: Allow inbound ssh & https connections
      vpc_id: "{{ awsnd_vpc_id }}"
      region: "{{ awsnd_base_region }}"
      rules:
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      tags:
        awsnd_guid: "{{ awsnd_guid }}"
